{
 "title": "Kintaba Dashboard Template",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Incident Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: INCIDENT_STATUS\n        status: [CLOSED]\n      }\n    ) {\n      ... on IncidentStatusReport {\n        groups {\n          status\n          items {\n            Time:startInterval\n            Closed:count\n          }\n        }\n      }\n    }\n  }"
    },
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: INCIDENT_STATUS\n        status: [OPEN]\n      }\n    ) {\n      ... on IncidentStatusReport {\n        groups {\n          status\n          items {\n            Time:startInterval\n            Open:count\n          }\n        }\n      }\n    }\n  }"
    }
   ]
  },
  {
   "title": "Open Incidents by Severity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: INCIDENT_SEVERITY\n        status: [OPEN]\n        severity: [SEV1]\n      }\n    ) {\n      ... on IncidentSeverityReport {\n        groups {\n          severity\n          items {\n            Time:startInterval\n            SEV1:count\n          }\n        }\n      }\n    }\n  }"
    },
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: INCIDENT_SEVERITY\n        status: [OPEN]\n        severity: [SEV2]\n      }\n    ) {\n      ... on IncidentSeverityReport {\n        groups {\n          severity\n          items {\n            Time:startInterval\n            SEV2:count\n          }\n        }\n      }\n    }\n  }"
    },
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: INCIDENT_SEVERITY\n        status: [OPEN]\n        severity: [SEV3]\n      }\n    ) {\n      ... on IncidentSeverityReport {\n        groups {\n          severity\n          items {\n            Time:startInterval\n            SEV3:count\n          }\n        }\n      }\n    }\n  }"
    }
   ]
  },
  {
   "title": "Postmortem Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: POSTMORTEM_STATUS\n        postmortemStatus: [DRAFT]\n      }\n    ) {\n      ... on PostmortemStatusReport {\n        groups {\n          postmortemStatus\n          items {\n            Time:startInterval\n            Draft:count\n          }\n        }\n      }\n    }\n  }"
    },
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: POSTMORTEM_STATUS\n        postmortemStatus: [PUBLISHED]\n      }\n    ) {\n      ... on PostmortemStatusReport {\n        groups {\n          postmortemStatus\n          items {\n            Time:startInterval\n            Published:count\n          }\n        }\n      }\n    }\n  }"
    },
    {
     "constant": 6.5,
     "dataPath": "report.groups",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: POSTMORTEM_STATUS\n        postmortemStatus: [REVIEWED]\n      }\n    ) {\n      ... on PostmortemStatusReport {\n        groups {\n          postmortemStatus\n          items {\n            Time:startInterval\n            Reviewed:count\n          }\n        }\n      }\n    }\n  }"
    }
   ]
  },
  {
   "title": "MTTR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "report",
     "queryText": "query ReportIncident {\n    report(\n      criteria: {\n        startTime: $startTime\n        endTime: $endTime\n        resolution: WEEK\n        type: INCIDENT_MITIGATION\n      }\n    ) {\n      ... on IncidentMitigationReport {\n        items {\n          Time:startInterval\n          Duration:timeToMitigation\n        }\n      }\n    }\n  }"
    }
   ]
  },
  {
   "title": "Open Incidents",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.company.incidents",
     "queryText": "query ViewerCompanyList {\n  viewer {\n    company {\n      incidents(filter:{includeStatus: OPEN}) {\n        count\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Open Incidents",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.company.incidents",
     "queryText": "query ViewerCompanyList {\n  viewer {\n    company {\n      incidents(filter:{includeStatus: OPEN}) {\n        Open:count\n      }\n    }\n  }\n}"
    },
    {
     "constant": 6.5,
     "dataPath": "viewer.company.incidents",
     "queryText": "query ViewerCompanyList {\n  viewer {\n    company {\n      incidents(filter:{includeStatus: CLOSED}) {\n        Closed:count\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "#Infra Incidents",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.company.incidents",
     "queryText": "query ViewerCompanyList {\n  viewer {\n    company {\n      incidents(filter:{includeStatus: OPEN, search: \"#infra\"}) {\n        Open:count\n      }\n    }\n  }\n}"
    },
    {
     "constant": 6.5,
     "dataPath": "viewer.company.incidents",
     "queryText": "query ViewerCompanyList {\n  viewer {\n    company {\n      incidents(filter:{includeStatus: CLOSED, search: \"#infra\"}) {\n        Closed:count\n      }\n    }\n  }\n}"
    }
   ]
  }
 ]
}